apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgetledger
  labels:
    app: budgetledger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budgetledger
  template:
    metadata:
      labels:
        app: budgetledger
    spec:
      containers:
        - name: budgetledger
          image: 047719652562.dkr.ecr.us-east-1.amazonaws.com/capstone_ecr
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://database-1.c9ke46ewy3ly.us-east-1.rds.amazonaws.com:3306/db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: adminadmin
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MySQL8Dialect
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
